### ISSUE TITLE
Persist partial QAA form in local storage

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#110]
The QAA form can be very long, and intermittent issues may prevent submission.  
When create a "New" QAA submission - let's store the QAA state in local storage so when the browser is refreshed, we can recover the progress.  

We should also add a button to clear the form, if we no longer need to keep the local stored state.

**Comment by ketankanhasoft** [comment]
Here is PR
https://github.com/savantly-net/franchise-manager/pull/118
