### ISSUE TITLE
QAA - Create tab on score card page with the summary of questions

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#116]
Should show all the question "NO's" and notes.  
The tab can be named "Action Plan".  

We can use or remove the existing score tab on the page header is it interferes 

Example showing the score tab

<img width="843" alt="image" src="https://user-images.githubusercontent.com/2660839/160478368-f1fa6062-7bd3-476c-9b36-cf84f50d0a9d.png">

For every question that has "NO" for an answer, we want to display the data in a table on the "Action Plan" tab - 

<img width="740" alt="image" src="https://user-images.githubusercontent.com/2660839/160479141-3b17c112-c9b7-4175-bf4d-886b98e61352.png">

**Comment by ketankanhasoft** [comment]
Here is PR
https://github.com/savantly-net/franchise-manager/pull/119
