### ISSUE TITLE
QAA: notes style

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#124]
Let's make the padding on the `Notes` label columns match the others.  
Also, let's make the the `Notes` label column only 1 column wide, and make the actual notes text area span 4 columns.  

![image](https://user-images.githubusercontent.com/2660839/161505633-0e1812d1-13dc-4067-9d00-d7aa7d305afa.png)

**Comment by ketankanhasoft** [comment]
Here is PR
https://github.com/savantly-net/franchise-manager/pull/133

**Comment by ketankanhasoft** [comment]
Here is PR
https://github.com/savantly-net/franchise-manager/pull/133
