### ISSUE TITLE
QAA: Image thumbnails

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#125]
Let's hide the blank image, when there is no image attachment.
Also, let's make the image thumbnail 100% of the column width.

![image](https://user-images.githubusercontent.com/2660839/161505955-ef830b6c-abc9-4e5a-a255-46803ab3c26f.png)

**Comment by ketankanhasoft** [comment]
Hello @jdbranham 
when we put 100% of thumbnail width then image is stretching this way.
![Sprout App (4)](https://user-images.githubusercontent.com/24564038/161526353-238fe135-195b-45cb-9aa9-a328db68d495.png)

**Comment by ketankanhasoft** [comment]
Here is PR
https://github.com/savantly-net/franchise-manager/pull/133

**Comment by ketankanhasoft** [comment]
Here is PR
https://github.com/savantly-net/franchise-manager/pull/133
