### ISSUE TITLE
QAA: section header

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#126]
Let's make the section header bold 

![image](https://user-images.githubusercontent.com/2660839/161506486-4213e8ec-1d8d-494a-936c-9be278fa6f3b.png)

**Comment by ketankanhasoft** [comment]
Here is PR
https://github.com/savantly-net/franchise-manager/pull/133

**Comment by ketankanhasoft** [comment]
Here is PR
https://github.com/savantly-net/franchise-manager/pull/133
