### ISSUE TITLE
QAA: score page style

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#127]
Let's put the section identifier all on one line - like `Section 1: A new section`. 
Let's make the section header/identifier a little larger/bold [h4?]  
Let's add padding or margin to put more space between the tabs and the score content.  

Also, when a new QA Submission is created, let's redirect to this score page by default.  

![image](https://user-images.githubusercontent.com/2660839/161507855-f51e570f-f1d0-43a4-8991-c25964fd11c0.png)

**Comment by ketankanhasoft** [comment]
Here is PR
https://github.com/savantly-net/franchise-manager/pull/133

**Comment by ketankanhasoft** [comment]
Here is PR
https://github.com/savantly-net/franchise-manager/pull/133
