### ISSUE TITLE
QAA: Images on "Action Plan"

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#128]
Let's add the image attachments on the "Action Plan" tab of the score page.  
We can add a new column, and the images should be at least 400px wide.  

Also, let's add the `section.order` and `question.order` as another column on the left side.   

So it looks similar to the edit/create page - ex. `1.2` or `2.5` , so the users can quickly identify them.   

![image](https://user-images.githubusercontent.com/2660839/161509815-4fa6c25a-ad6c-4445-8dec-31d6598800c9.png)

**Comment by ketankanhasoft** [comment]
Here is PR
https://github.com/savantly-net/franchise-manager/pull/133

**Comment by ketankanhasoft** [comment]
Here is PR
https://github.com/savantly-net/franchise-manager/pull/133
