### ISSUE TITLE
User Selector Component updates

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#154]
The user selection component should operate the same everywhere.

AC - 

- the user selector should have a value of the user's unique identifier (item_id)
- the user selector should display the user's name

**Comment by ketankanhasoft** [comment]
Here is PR
https://github.com/savantly-net/franchise-manager/pull/158

**Comment by ketankanhasoft** [comment]
Here is PR 
https://github.com/savantly-net/franchise-manager/pull/158
