### ISSUE TITLE
QAA: All category names should display

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#159]
All the questions are displayed, but only the first category name is being displayed.  

We should display the category name, once for each group of questions with the same category.

![image](https://user-images.githubusercontent.com/2660839/165031304-11ec5593-1400-4b8e-a23b-23dd64aedcf8.png)

**Comment by ketankanhasoft** [comment]
Here is PR
https://github.com/savantly-net/franchise-manager/pull/161
