### ISSUE TITLE
QAA: Print View

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#160]
When printing, can we hide the 3 columns on the right, and make the left column thinner?  
It's difficult to view the question.  

Also, it's only printing the first page of content. 
Let's make it print all pages of the document.  

![image](https://user-images.githubusercontent.com/2660839/165032389-1ed6c0aa-a448-41a9-a0f3-2c9f5650fc89.png)

**Comment by ketankanhasoft** [comment]
Here is PR
https://github.com/savantly-net/franchise-manager/pull/161

**Comment by jdbranham** [comment]
It's close - can we make these 2 columns more narrow in the print view? 

![image](https://user-images.githubusercontent.com/2660839/165217430-35e56e3e-04f9-472c-9c5b-b925fabfbd3b.png)
