### ISSUE TITLE
QAA: delete submission button isn't working

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#175]
When clicking the delete button on the submission list view, it should prompt the user to confirm and delete.
It doesn't seem to do anything

![image.png](https://images.zenhubusercontent.com/587907ba51aa2c3057720c81/6c7c87d9-e17c-4271-bef1-bafa45382ac7)

**Comment by ketankanhasoft** [comment]
okay, one more thing here is when user don't have permission as admin in QAI (FM_QAI_ADMIN), user will not able to see delete button.

**Comment by ketankanhasoft** [comment]
okay, so here user will able to delete qai if user has right (FM_QAI_ADMIN).
