### ISSUE TITLE
Add "Vendor" management 

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#49]
We need to manage a list of vendors with contact information.  
Let's use the typical Entity page, as we do with other collections, with "editor" and "viewer" components.  
We'll start with just a basic form with simple text inputs, and refine it in another iteration.  

We'll also add a menu item to access the vendor list.  

The API is located at `/api/fm/vendor`  [check swagger for more detail]

The `Vendor` entity has a `typeid` field that should be the id of the `Vendor Type` entity [`/api/fm/vendor-type`].  

These are the editable fields -  
- name
- phoneNumber
- emailAddress
- mailingAddress
- notes
- typeId

**Comment by ketankanhasoft** [comment]
Hello jeremy

we are not able to find the apis in server and locally as well, can you please check and let us know.

**Comment by ketankanhasoft** [comment]
hay @jdbranham 
I have tried to implement put (update) API but it does not work, please check this once for your end, let me know if I'm missing anything from my end.
