### ISSUE TITLE
Vendor Type management

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#50]
Related to issue #49 

We need to manage a list of "Vendor Types".  
The API is located at `/api/fm/vendor-type`  

We'll start with a basic Entity Page like the other collections we manage.  
The ID of the `Vendor Type` will be used as a selection value in the `Vendor` entity.   

There will be a single editable field called `name`

**Comment by jdbranham** [comment]
The vendor type API is accessible now -  

![image](https://user-images.githubusercontent.com/2660839/150001925-9c1fcce5-22fb-436c-9805-3c259e64309e.png)

**Comment by ketankanhasoft** [comment]
hay @jdbranham 
I have tried to implement put (update) API but it does not work, please check this once for your end, let me know if I'm missing anything from my end.

**Comment by ketankanhasoft** [comment]
Hey @jdbranham 
Here is PR.
https://github.com/savantly-net/franchise-manager/pull/62
