### ISSUE TITLE
Use standard DataTable editor for Location Fees

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#60]
On the Location editor page -  

When adding a "Fee" to the location -  
Let's use a standard DataTable control to add/remove the Fee Items.   

The current editing interface isn't friendly, and is difficult to modify the data - There's also no way to delete an entry.    

![image](https://user-images.githubusercontent.com/2660839/150051691-9dabec34-7ba6-4fcf-a95b-1cbddee7bb91.png)

**Comment by ketankanhasoft** [comment]
Hey @jdbranham 

standard DataTable uses different routes for all actions and in location fees everything we manage in a single route.
If we use the standard data table here we need to change route and we lost other tabs data.

**Comment by ketankanhasoft** [comment]
Hay @jdbranham 
Here is PR.
https://github.com/savantly-net/franchise-manager/pull/63
