### ISSUE TITLE
Hours editing page style

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#65]
The html elements look squished together.  
Can we update the style to give a better visual appearance?  

![image](https://user-images.githubusercontent.com/2660839/152013470-325bd868-74ed-40d9-84ed-ef5399c8ef08.png)

**Comment by ketankanhasoft** [comment]
Hey @jdbranham 
i have added PR on this card.
https://github.com/savantly-net/franchise-manager/issues/66
