### ISSUE TITLE
Modified hours layout

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#66]
When adding several modified hours, it wraps and the delete icon doesnt line up well.  

Can we make this a single column of modified hour entries, and fix the delete icon alignment?  

![image](https://user-images.githubusercontent.com/2660839/152014119-f341f4ca-f01a-42cc-aa1c-ccf6b00af116.png)

**Comment by ketankanhasoft** [comment]
Hey @jdbranham 
Here is PR, please have a look.
https://github.com/savantly-net/franchise-manager/pull/72
