### ISSUE TITLE
Remove terminal form fields 

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#68]
Let's remove the terminal form fields from the location editor - 

![image](https://user-images.githubusercontent.com/2660839/152031816-183a1f2a-8899-4210-8399-c5214c40d545.png)

**Comment by ketankanhasoft** [comment]
Hey @jdbranham 
Here is PR, please have a look.
https://github.com/savantly-net/franchise-manager/pull/73
