### ISSUE TITLE
Add new location form fields

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#69]
We need to add a few form fields to the location editor.   
Feel free to organize the new form fields in a way that makes sense. We can re-arrange them in a future iteration if necessary.  

## Field name: smallWare
Display name: Small Ware
Type: Free text input

## Field name: kes
Display name: KES
Type: Free text input

## Field name: realEstateType
Display name: Real Estate Type
Type: Dropdown box
Options: 
- Downtown
- Residential
- University
- Retail Center

## Field name: stage
Display name: Stage
Type: Dropdown box
Options: 
- Franchise Aggreement
- Site Approval
- LOI Submitted
- Lease Sign
- Design / Permitting
- Under Construction

## Field name: distributionCenter
Display name: Distribution Center
Type: Free text input

## Field name: training
Display name: Training
Type: Dropdown box
Options: 
- Self
- Corporate

![image](https://user-images.githubusercontent.com/2660839/152033446-71219b78-5f5a-43ae-9875-a9562b44cfba.png)

**Comment by ketankanhasoft** [comment]
hey @jdbranham 
Here is PR, please have a look.
https://github.com/savantly-net/franchise-manager/pull/74
