### ISSUE TITLE
Sort locations on Store Visit form

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#70]
The locations should be sorted by "display name" on the store visit creation page -  

![image](https://user-images.githubusercontent.com/2660839/152064105-391aef83-8f04-4bd8-8e74-dcfc7fdeb84d.png)

**Comment by ketankanhasoft** [comment]
hey @jdbranham 
Here is PR, please have look.
https://github.com/savantly-net/franchise-manager/pull/71
