### ISSUE TITLE
Add "Open Intervals" to location editor

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#76]
Similar to the "Hours" editor, we need to add an component to the Location Editor that manages a list of date ranges that indicate when a location has been open.   

The Location API has been updated, and the location json now contains a field `openDateIntervals`  

https://api-franchise-manager.herokuapp.com/swagger-ui/index.html?configUrl=../v3/api-docs/swagger-config#/location-api/LocationApiUpsertOne

Example -  
```
{
...
  "openDateIntervals": [
    {
      "start": "2020-01-01",
      "end": "2020-11-01",
    },
    {
      "start": "2021-01-01",
      "end": null
    }
  ]
}
```

It can look something like this -  
![image](https://user-images.githubusercontent.com/2660839/153113556-6f643bcb-7507-4fd6-ae66-1fa927ba527d.png)

Feel free to organize the field controls on the location editor, to make the user experience better.

**Comment by ketankanhasoft** [comment]
Here is PR.
https://github.com/savantly-net/franchise-manager/pull/78
