### ISSUE TITLE
The QAI Submission should be combined into 1 long form

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#83]
We need to refactor the "QAI Section Submission" process to be one long form, instead of separate submissions.
The Sections have an `order` property we can use to determine the order to display them.

Mockup - 

![image](https://user-images.githubusercontent.com/2660839/154786884-6a4e082d-32dd-41a4-96d4-3f787ee9b02d.png)

A new API will be developed for this data -  
`/api/fm/qaa/submission`  

Each section submission data should be added to an array when posted to the API.

Example POST body -  
```
{
  "locationId": "123",
  "dateScored": "2022-02-19T04:40:28.389Z",
  "managerOnDuty": "John Doe",
  "fsc": "user1",
  "responsibleAlcoholCert": "lorem ipsum",
  "sections": [
    {
      "sectionId": "string",
      "locationId": "string",
      "status": "DRAFT",
      "answers": [
        {
          "questionId": "string",
          "value": "YES",
          "notes": "string",
          "attachments": []
        }
      ],
      "guestAnswers": [
        {
          "answers": [
            {
              "guestQuestionId": "string",
              "value": "YES"
            }
          ],
          "notes": "string",
          "attachments": []
        }
      ]
    }
  ]
}
```

**Comment by ketankanhasoft** [comment]
Hello @jdbranham ,

i am bit confused here, is it a new screen to create or we need to modify the older one.

![Screenshot from 2022-02-21 11-09-11](https://user-images.githubusercontent.com/24564038/154896881-c88f9ade-6040-45a9-a063-7a115ab0f41e.png)

**Comment by ketankanhasoft** [comment]
Hey @jdbranham 
I have created a design like the below image.
I did not find API (/api/fm/qaa/submission), I have taken the latest pull from the main branch.

![screenshot-localhost_3001-2022 02 24-14_38_27](https://user-images.githubusercontent.com/24564038/155493682-3027b2dc-fb0d-402f-a149-7898fe222450.png)

**Comment by ketankanhasoft** [comment]
Here is PR.
https://github.com/savantly-net/franchise-manager/pull/90

**Comment by jdbranham** [comment]
That's ok - the users will be taking new pictures for each attachment, and they'll have different names.
I'll create an issue in the backlog to fix that on the backend.
