### ISSUE TITLE
Only show question category once

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#92]
Only show the question category one time, above the first question with that category.  
We can order the questions by the `order` field ascending.

![image](https://user-images.githubusercontent.com/2660839/158533283-df48a386-8f6a-4d60-a116-15bba21997d1.png)

**Comment by ketankanhasoft** [comment]
@jdbranham 
I have checked the code but in section API we are getting order parameter as 0, so can you please check at once and let me know if I'm missing anything.

**Comment by jdbranham** [comment]
this is done.
