### ISSUE TITLE
Add "N/A" to Guest Answer options

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/franchise-manager#93]
The sponsor would like to add "N/A" back to the list of answer options for the guest question.

![image](https://user-images.githubusercontent.com/2660839/158533559-1d65ea20-ea02-4f5c-a969-8f09059121b5.png)

**Comment by ketankanhasoft** [comment]
@jdbranham I have passed the "N/A" option with the value "NA" but I'm getting errors like the below files.
![screenshot-localhost_8080-2022 03 16-15_35_04](https://user-images.githubusercontent.com/24564038/158565956-c79f8c0d-3dd1-42a3-a697-c67cf8c1ae40.png)

**Comment by ketankanhasoft** [comment]
@jdbranham Here is PR, https://github.com/savantly-net/franchise-manager/pull/97

**Comment by jdbranham** [comment]
Thanks Ketan - I'll create a task for the backend to add 'NA' to the accepted enumeration values.
